apiVersion: v1
kind: ConfigMap
metadata:
  name: contour-external
  namespace: mink-system
data:
  contour.yaml: |
    disablePermitInsecure: false
    leaderelection:
      configmap-name: leader-elect-external
      configmap-namespace: mink-system
