apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-nodejs
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: dockerfile:///helloworld-nodejs
        name: main
        env:
        - name: TARGET
          value: "Node.js Sample v1"
