apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: chart
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/release.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - image: gcr.io/jenkinsxio/builder-go
          name: next-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step next-version --use-git-tag-only
        - image: gcr.io/jenkinsxio/builder-go
          name: update-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step tag --version $(cat VERSION) --no-apply
        - image: gcr.io/jenkinsxio/builder-go
          name: tag-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step tag --version $(cat VERSION)
        - name: jx-variables
          resources: {}
        - name: release-binary
          resources: {}
        - name: chart-docs
          resources: {}
        - image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: changelog
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh
            jx step changelog --verbose --header-file=hack/changelog-header.md --version=$VERSION --rev=$PULL_BASE_SHA --output-markdown=changelog.md --update-release=false
        - name: upload-binaries
          resources: {}
        - image: google/cloud-sdk:slim
          name: build-and-push-image
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh
            /workspace/source/build.sh
        - name: release-chart
          resources: {}
        - image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: promote-release
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh
            ./promote.sh
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
